/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_infobright_io_WindowsNamedPipe */

#ifndef _Included_com_infobright_io_WindowsNamedPipe
#define _Included_com_infobright_io_WindowsNamedPipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_infobright_NamedPipe
 * Method:    serverCreate
 * Signature: (Ljava/lang/String;ZZIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_infobright_io_WindowsNamedPipe_serverCreate
  (JNIEnv *, jclass, jstring, jboolean, jboolean, jint, jlong);

/*
 * Class:     com_infobright_NamedPipe
 * Method:    fileRead
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_infobright_io_WindowsNamedPipe_fileRead
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_infobright_NamedPipe
 * Method:    fileWrite
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_infobright_io_WindowsNamedPipe_fileWrite
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_infobright_NamedPipe
 * Method:    fileClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_infobright_io_WindowsNamedPipe_fileClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_infobright_NamedPipe
 * Method:    clientCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_infobright_io_WindowsNamedPipe_clientCreate
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
